name: spotify
channels:
  - conda-forge
dependencies:
  - python=3.9
  - selenium=4.15.2
  - pandas=2.1.3
  - numpy=1.26.2
  - python-decouple=3.8
  - requests=2.31.0
  - bs4=4.12.2
  # For connecting to PostgreSQL
  - sqlalchemy=2.0.22
  - pip
  - pip:
      - psycopg2
      - crontab